##There are two functions below. Use makeCacheMatrix to generate a special 
##special matrix and cache its inverse. The use  the cacheSolve function to
## calculate the inverse of the special matrix generated by makeCachematrix.
##It first checks to see if the inverse has been calculated. If it has, it
##retrieves the data from the cache. If it has not been calculated, it will
##determine the inverse of the matrix with the solve function. 


## makeCacheMatrix is a function that creates a special matrix that
##can cache its inverse. 

makeCacheMatrix <- function(x = matrix()) {
                m <- NULL
                set <- function(y) {
                        x <<- y
                        m <<- NULL
                }
                get <- function() x
                setinverse <- function(solve) m <<- solve
                getinverse <- function() m
                list(set = set, get = get,
                     setinverse = setinverse,
                     getinverse = getinverse)
        }


## cacheSolve is a function that calculates the inverse of the special matrix
##returned by makeCacheMatrix above. 
##It first checks to see if inverse has been calculated. If it has it will 
##return the data in the cache. If not it will perform the calculation. 

cacheSolve <- function(x, ...) {
        m <- x$getinverse()
        if(!is.null(m)) {
                message("getting cached data")
                return(m)
        }
        data <- x$get()
        m <- solve(data)
        x$setinverse(m)
        m
}

## Return a matrix that is the inverse of 'x'
